# Generated by Django 3.2 on 2021-04-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('telephone_number', models.IntegerField(null=True, verbose_name='номер телефона')),
                ('position', models.CharField(max_length=200, verbose_name='должность')),
                ('date_of_interview', models.DateField(null=True, verbose_name='дата собеседования')),
                ('duration', models.IntegerField(null=True, verbose_name='срок задания')),
                ('interviewer_name', models.CharField(max_length=200, verbose_name='руководитель')),
                ('interviewer_position', models.CharField(max_length=200, verbose_name='Должность руководителя')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='отметка')),
                ('created', models.DateField(null=True, verbose_name='дата и время')),
                ('interviewer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.applicant', verbose_name='руководитель')),
            ],
        ),
    ]
